### ISSUE TITLE
Running the ansible 

### ISSUE THREAD

**Issue by donydonald1** [sebdanielsson/ansible-role-cloudflared#71]
Hello,
Sorry, i am very new to ansible and was wondering how to set this up on my env. 
Any help would be appreciated.
Thanks

**Comment by sebdanielsson** [comment]
Did you try the following instructions?

    - hosts: localhost

      roles:
        - role: sebdanielsson.cloudflared
          vars:
            cloudflare_tunnel_enable: true
            cloudflare_tunnel_credential: <your_cf_tunnel_credential>
          state: present

**Comment by donydonald1** [comment]
Well i don't know how to pass the info and command for Ansible to apply it

**Comment by sebdanielsson** [comment]
For general Ansible help I would take a look at the official [documentation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html#playbooks-intro). They'll probably do a better job explaining it than me. But the to just run a playbook you can run `ansible-playbook playbook.yml`.

**Comment by sebdanielsson** [comment]
There are multiple ways of handling this. You could use Ansible Vault for example. For my simple use cases I use environment variables together with 1Password service accounts.

https://www.redhat.com/sysadmin/ansible-playbooks-secrets
